---
title: "Лабораторная работа №2. Предварительный анализ данных и модель регрессии"
author: "С.А.Суязова (Аксюк), [sa_aksyuk@guu.ru](mailto:sa_aksyuk@guu.ru)"
date: "`r format(Sys.time(), '%d %b, %Y')`"
tags: "R[^1], r-project, RStudio"  
output:
  word_document:
    reference_docx: ./Шаблон.docx
    toc: yes
---

Ключевые слова: R[^1], r-project, RStudio  

Примеры выполнены R версии `r paste0(R.version$major, '.', R.version$minor)`, «`r R.version$nickname`».  

Версия RStudio: 1.4.1717.  

Все ссылки действительны на 8 февраля 2021 г.  

Репозиторий с материалами к курсу: [github.com/aksyuk/R_data_glimpse](https://github.com/aksyuk/R_data_glimpse)   

Файл с макетом кода для этой практики: `.Labs/lab-02_before.R`    

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    comment = "#>",
    collapse = TRUE
)

```

##### Новая страница    




# Лабораторная работа №2: Предварительный анализ данных и модель регрессии   



## Философия опрятных (tidy) данных   

\ \ \ \ \ Если вы уже работали со статистикой от сбора до презентации результатов анализа, то наверняка заметили, что 80% времени уходит на подготовку данных. Понятие "опрятных данных" было введено с целью упорядочить шаги по такой подготовке, сократить время, затрачиваемое на них, и облегчить дальнейший анализ. Этот процесс в западной литературе называется "data tidying", по-русски получается длиннее: "структурирование и приведение в порядок наборов данных" [^2]. Требования к опрятным данным очень похожи на требования третьей нормальной формы в базах данных:   

1. Каждая переменная формирует столбец.  

1. Каждое наблюдение формирует строку.  

1. Каждый тип единицы наблюдения формирует таблицу.   

\ \ \ \ \ К счастью, в R есть удобные средства структурирования данных -- они сгруппированы в коллекцию пакетов *tidyverse*. Пакеты из этой коллекции построены по принципу единой грамматики, в которой таблицы являются подлежащими, а действия над ними -- глаголами. Мы рассмотрим средства пакета `dplyr`: функции непосредственной манипуляции данными. Но для начала остановимся на важной детали -- правилах именования переменных.   

\ \ \ \ \ Формально в R действуют несколько ограничений на имена:

* имя должно начинаться с буквы;  

* имя должно содержать только буквы, цифры, подчёркивания и точки;   

* имя не должно совпадать с именами системных констант (`pi`);   

* крайне нежелательно совпадение имён пользовательских объектов с именами функций пакетов R.   

\ \ \ \ \ Но это ещё не всё. Хороший код не просто формально и стилистически верен, но и понятен. Поэтому содержательные имена -- хороший тон не только для переменных, но и для столбцов таблиц. Удачно подобранные имена ускоряют написание кода, однако слишком длинные могут сделать его нечитаемым. Так или иначе, выбираете вы содержательные имена или рискуете запутаться в переменных `my.val`, `my.val.1` и прочих случайных сочетаниях символов, главное -- действовать последовательно. Остановитесь на стиле написания имён, который нравится именно вам:    

`пишите_все_имена_в_змеином_регистре`  
`илиИспользуйтеВерблюжийРегистр`   
`далее.имена.в.основном.написаны.через.точки`  
`Только.не_используйтеВсеВперемешку`  

\ \ \ \ \ И помните, что люди из Google уже написали руководства по стилю программирования на всех языках программирования, в том числе и на R [^3].    



## Графические системы в R      

\ \ \ \ \ R предоставляет пользователю широкие графические возможности. Если говорить о визуализации количественных данных, то на данный момент в R существуют три основных графических системы, которые принципиально отличаются друг от друга [^4]:  

1. **Встроенная система «base»** [^5]. Построена по принципу конструктора: различные функции вызываются последовательно и дополняют график. При этом обязательно использование одной базовой функции, которая определяет тип графика и данные и создаёт область графика. Такими основными функциями являются, например, `plot()`, `boxplot()`, `curve()`.  

1. **Система «trellis»**, реализованная в пакете **«lattice»** [^6]. Была создана специально для изображения кросс-секционных данных и направлена в основном на создание графиков по категориям значений. В отличие от «base», подавляющее большинство графиков «lattice» строится вызовом одной функции, и после создания графика его сложно изменить, например, добавив подписи осей, и нельзя дополнить новой порцией точек или кривых. С другой стороны, графические параметры в «lattice» настроены заранее и оптимизированы для представления нескольких графиков на одной панели.   

3.	**Система «ggplot»** (пакет **«ggplot2»** [^7]). Реализует грамматику графиков, предложенную Леландом Уилкинсоном. График собирается как «предложение» из нескольких функций, первая из которых задаёт исходные данные («существительное»), вторая -- их представление («глагол»), остальные добавляют на график дополнительные слои («прилагательные»). Как и в «lattice», система автоматически управляет графическими параметрами. Также функции «ggplot2» могут трансформировать данные (например, шкалы показателей) и изменять их под различные координатные системы.   

\ \ \ \ \ Функции трёх графических систем не сочетаются друг с другом. Поэтому прежде чем строить график, стоит понять, какие принципы изображения необходимы в данном случае:     

1.	На начальной, разведочной, стадии анализа, для представления данных, не сгруппированных по категориям, подходит «base».  

1.	Система «lattice» поможет представить данные с переменными-факторами, представив графики по категориям на отдельных панелях.  

1.	Система «ggplot2» построит более сложные визуализации, например, с пересчётом в другие координаты; нанесёт данные на географическую карту; сохранит график со всеми настройками в виде отдельного объекта в рабочем пространстве R.  
\ \ \ \ \ В R существует много готовых функций на базе перечисленных пакетов, которые служат для создания специальных графиков. Некоторые из них:   

* мозаичные графики и графики ассоциаций для визуализации категориальных данных: пакет «vcd» [^8];   

* самоорганизующиеся карты Кохонена: пакет «kohonen» [^9];   

* «тепловые карты» для визуализации схожести объектов и результатов кластерного анализа: пакет «gplots» [^10];   

* интерактивные трёхмерные графики: пакет «rgl» [^11];   

* фазовые плоскости одно- и двумерных автономных систем дифференциальных уравнений: пакет «phaseR» [^12].   

\ \ \ \ \ Далее мы рассмотрим работу с графическими системами «lattice» и «ggplot2».   



## Предварительный анализ и визуализация данных по импорту за 2019 год    

\ \ \ \ \ **Пример №1**. Используем данные импорта  






[//]: # Концевые сноски

[^1]: R Core Team (2015). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL <https://www.R-project.org/>  

[^2]: Олег Замощин [@turegum](https://habr.com/users/turegum/). Data tidying: Подготовка наборов данных для анализа на конкретных примерах / habr.com, 24 января 2015. URL: <https://habr.com/ru/post/248741/>   

[^3]: Руководство по стилю программирования на R. URL: <https://drive.google.com/open?id=1zS-jyjokHEL_IjCPaKPPbrJU89VHzzae>   

[^4]: Roger D. Peng. Материалы курса «Exploratory Data Analysis» Университета Джонса Хопкинса на портале coursera.org, доступные в репозитории на github.com: <https://github.com/rdpeng/courses/tree/master/04_ExploratoryAnalysis>

[^5]: R Core Team (2015). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL: <https://www.R-project.org/>   

[^6]: Sarkar, Deepayan (2008) Lattice: Multivariate Data Visualization with R. Springer, New York. ISBN 978-0-387-75968-5   

[^7]: H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2009   

[^8]: Блог Р.Кабакова Quick-R: Visualizing Categorical Data. URL: <http://www.statmethods.net/advgraphs/mosaic.html>   

[^9]: Self-Organising Maps for Customer Segmentation using R / R-bloggers.com. URL: <http://www.r-bloggers.com/self-organising-maps-for-customer-segmentation-using-r/>   

[^10]: Sebastian Raschka. A short tutorial for decent heat maps in R. URL: <http://sebastianraschka.com/Articles/heatmaps_in_r.html>   

[^11]: Garrett Grolemund. Quick list of useful R packages / support.rstudio.com. URL: <https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages>   

[^12]: Markus Gesmann. Phase plane analysis in R / magesblog.com. URL: <http://www.magesblog.com/2014/11/phase-plane-analysis-in-r.html>   